README.md, api/handlers/accountinfo_handler.go, api/handlers/blockinfo_handler.go, api/handlers/chart_handler.go, api/handlers/contractinfo_handler.go, api/handlers/nodeinfo_handler.go, api/handlers/types.go, cleardb.sh, cmd/chart_service/cmd/root.go, cmd/chart_service/cmd/server.json, cmd/node_service/cmd/root.go, cmd/node_service/cmd/server.json, cmd/scan_server/cmd/root.go, cmd/scan_server/cmd/server.json, cmd/seele_syncer/cmd/root.go, cmd/seele_syncer/cmd/server.json, database/client.go, log/log.go, node/findnode.go, rpc/seele_rpc.go, syncer/account_process.go, syncer/tx_process.go
fix some bugs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/4)
=> fix some bugs

log/log.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/7)
=> fix log path

database/client.go, rpc/api_types.go, syncer/tx_process.go
The To is null, when we create a contract . But it's not null from the page display.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/6)
=>  fix create contract To is not null

database/types.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/8)
=> fix the type of transaction is not assigned

api/handlers/chart_handler.go, database/client.go, database/types.go, rpc/api_types.go, syncer/block_process.go, syncer/database.go, syncer/syncer.go, syncer/tx_process.go
1、fix block lost 
2、fix block repetition
3、fix other
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/9)
=> fix block lost and repetition

database/client.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/10)
=> fix removetxs by shard

syncer/account_process.go, syncer/syncer.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/11)
=> fix the tx count and the tx count of the account is inconsistent

database/client.go
fix remove block and tx bug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/12)
=> fix remove block and tx bug

api/handlers/accountinfo_handler.go, api/handlers/contractinfo_handler.go, api/handlers/database.go, syncer/account_process.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/14)
=> fix tx count bug

api/handlers/types.go, database/types.go, syncer/tx_process.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/13)
=> add receipt

syncer/syncer.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/15)
=> fix the genesis block lost

syncer/syncer.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/16)
=> fix genesis block lost bug

syncer/syncer.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/17)
=> fix checkOlderBlocks have 0 block

database/client.go, syncer/database.go, syncer/syncer.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/18)
=>  fix the 0 block time is 48 year ago

node/findnode.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/19)
=> fix show secret address

api/handlers/types.go, database/types.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/21)
=> change the type of block

database/client.go, database/client_test.go, syncer/database.go, syncer/tx_process.go
fix repetition transaction 
change to batch add transaction
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/23)
=> fix repetition transaction

rpc/errors_test.go
add some unittests for rpc.errors
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/24)
=> add some unittests for rpc.errors

api/handlers/accountinfo_handler.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/26)
=> fix shard 20 can't show accounts

api/handlers/database.go, api/handlers/types.go, database/client.go
Add a block structure field.[key:Nonce\fee\Total fee\reward]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/28)
=> Add a block structure field

api/handlers/blockinfo_handler.go, api/handlers/database.go, api/routers/router.go, database/client.go
The average time blocks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/32)
=> The average time blocks

api/handlers/blockinfo_handler.go, api/handlers/database.go, api/routers/router.go, database/client.go
Tps calculation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/34)
=> Tps calculation

api/handlers/accountinfo_handler.go, api/handlers/database.go, api/handlers/types.go, api/routers/router.go, database/client.go
Home page asset account ranking API
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/31)
=> Home page asset account ranking API

api/handlers/blockinfo_handler.go, api/handlers/database.go, cmd/scan_server/cmd/server.json, database/client.go
Last Block  api
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/36)
=> Last Block api

api/handlers/accountinfo_handler.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/37)
=> fix miners counts

api/handlers/blockinfo_handler.go, api/handlers/database.go, api/handlers/types.go, database/client.go
Lastblock api
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/38)
=> Lastblock api

api/handlers/types.go
=> Account Balance list API

api/handlers/blockinfo_handler.go, api/handlers/database.go, database/client.go
30 days trading history data api
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/39)
=> 30 days trading history data api

database/client.go
=> BlockChain Txs The sorting

database/types.go, syncer/account_process.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/44)
=> fix miners total earning

rpc/api_types.go, rpc/seele_rpc.go, rpc/seele_test.go
modify some rpc call to seele node
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan-api/46)
=> modify some rpc call to seele node

database/types.go, rpc/api_types.go, rpc/client.go, rpc/seele_rpc.go, rpc/seele_rpc_test.go, syncer/syncer.go
Update the RPC calls seele node and synchronous debt structure to block in the table
=> Update the RPC calls seele node and synchronous debt structure to block in the table

syncer/syncer.go
=> Repair the miners information

api/routers/router.go, database/client.go, syncer/syncer.go
=> Repair the TPS

api/handlers/types.go
=> Block API add debt statistics

api/handlers/types.go
Transaction details Add debt hash
=> Transaction details Add debt hash

api/handlers/types.go
Trading paging list add debt hash
=> Trading paging list add debt hash

database/client.go, database/types.go, rpc/seele_rpc.go, syncer/database.go, syncer/syncer.go, syncer/tx_process.go
Update the RPC calls seele nodes, Add debt structure
=> Update the RPC calls seele nodes, Add debt structure

syncer/tx_process.go
fix insert nil txs and nil debts into mongodb print error log, nil data should not be inserted
=> fix wrong error log print

api/handlers/blockinfo_handler.go, api/handlers/database.go, api/handlers/types.go, api/routers/router.go, database/client.go
Add block debt statistics interface api
=>  Add block debt statistics interface api

rpc/seele_rpc.go, rpc/seele_rpc_test.go, syncer/syncer.go
Replace "CurrentBlock()" with "CurrentBlockHeight() "
=> Replace CurrentBlock() with CurrentBlockHeight()

syncer/syncer.go
Repair synchronous miners seele node to be obtained
=> Repair synchronous miners seele node to be obtained

database/client.go
Optimize the 30 day tx history function to make the api faster
=> Optimize the 30 day tx history function

api/routers/router.go, database/client.go
fix 30 days history error;
fix blockTxsTps error.
=> fix errors

database/client.go
=> fix 30 days history

database/client.go
=> fix blockTxsTps bug

api/handlers/blockinfo_handler.go, api/handlers/database.go, database/client.go, database/types.go
optimize 30 days response time
=> optimize 30 days response time

api/handlers/blockinfo_handler.go, database/types.go
=> fix display order

syncer/account_process.go, syncer/account_process_test.go, syncer/syncer.go
Repair synchronous problem seele node and income miners
=> Repair synchronous problem seele node and income miners

syncer/tx_process.go
=> Optimize the debt logic

api/handlers/types.go, database/client_test.go, database/types.go, database/types_test.go, rpc/api_types.go, rpc/seele_rpc.go, rpc/seele_rpc_test.go, syncer/tx_process.go
add some empty values before and some uint-tests
=> add some empty values before and some uint-tests

syncer/account_process.go
=> Repair miners revenue

database/client.go
Repair Pendingtxs sequence display bug
=> fix a bug in pendingtxs sequence display

cmd/scan_server/cmd/server.json, database/client.go
Repair the last block of time api
=> Repair the last block of time api

api/handlers/blockinfo_handler.go, api/routers/router.go, database/client.go, database/types.go, database/types_test.go, syncer/block_process.go, syncer/database.go, syncer/tx_process.go
1. store last two blocks information by shard;
2. get last two blocks by timestamp to get product rate;
3. the average response speed will be  within 100ms of the api "/blockprotime"
=> optimize get last block product rate api

database/client.go
=> Optimization TPS api

api/handlers/blockinfo_handler.go, api/handlers/database.go, database/client.go, syncer/database.go, syncer/tx_process.go, syncer/tx_process_test.go
the api will response in 100ms
=> optimize 30 days transaction history

database/client.go
remove all of the transaction history before the limit date
=> optimize remove the transaction history

cmd/seele_syncer/cmd/config_test.go, cmd/seele_syncer/cmd/root.go, cmd/seele_syncer/cmd/server1.json, cmd/seele_syncer/cmd/server2.json, cmd/seele_syncer/cmd/testfile/server1_test.json, cmd/seele_syncer/cmd/testfile/server2_test.json, rpc/seele_rpc_test.go, syncer/config.go
add database mode, prepare for mongodb replset mode
=> modify syncer config file

api/handlers/accountinfo_handler.go, cmd/chart_service/cmd/server1.json, cmd/chart_service/cmd/server2.json, cmd/chart_service/cmd/testfile/server1_test.json, cmd/chart_service/cmd/testfile/server2_test.json, cmd/node_service/cmd/server1.json, cmd/node_service/cmd/server2.json, cmd/node_service/cmd/testfile/server1_test.json, cmd/node_service/cmd/testfile/server2_test.json, cmd/seele_syncer/cmd/server2.json, cmd/seele_syncer/cmd/testfile/server1_test.json, cmd/seele_syncer/cmd/testfile/server2_test.json
1. modify shardnum from 20 to 2
2. modefy default rpc url
=> modify shardnum from 20 to 2

database/client.go
=> format database/client.go

api/handlers/types.go
Repair account assets accounted for
=> Repair account assets accounted for

syncer/syncer.go
=> remove zero block sync logic

rpc/seele_rpc.go
=> Get rid of timestamp

rpc/seele_rpc.go, syncer/account_process.go
=> fix seele_getBalance Rpc

cmd/seele_syncer/cmd/server1.json, database/client.go, database/types.go, syncer/account_process.go, syncer/database.go, syncer/syncer.go
Refactoring synchronization code and fix a bug
=> Refactoring synchronization code and fix a bug

database/types.go
Add the transaction GasPrice, GasLimit fields
=> Add the transaction GasPrice, GasLimit fields

api/handlers/blockinfo_handler.go, api/handlers/types.go, database/types.go, syncer/block_process.go, syncer/tx_process.go
=> fix block Txfee

api/handlers/blockinfo_handler.go, api/routers/router.go, cmd/seele_syncer/cmd/server1.json, database/client.go, database/types.go, syncer/database.go, syncer/tx_process.go
=> Add the average gasprice API

api/handlers/blockinfo_handler.go, database/client.go, database/types.go, syncer/database.go, syncer/tx_process.go
Add the highest and the lowest gas API
=> Add the highest and the lowest gas API

api/handlers/blockinfo_handler.go
=> fix integer divide by zero

syncer/account_process.go
=> Lock repair synchronization

api/handlers/blockinfo_handler_test.go
Add the Benchmark test LastBlock API
=> Add the Benchmark test LastBlock API

api/handlers/blockinfo_handler_test.go
Transaction statistics API and TPS API to add Benchmark test
=> Transaction statistics API and TPS API to add Benchmark test

api/handlers/blockinfo_handler_test.go
account count api 、contract count api 、Transaction History count  api  to add Benchmark test
=> account count api、contract count api 、Transaction History count  api  to add Benchmark test

api/handlers/accountinfo_handler_test.go
Account Balance Rankings api and Miner Revenue Rankings api to add Benchmark test
=> Account Balance Rankings api and Miner Revenue Rankings api to add Benchmark test

api/handlers/accountinfo_handler.go, api/handlers/contractinfo_handler.go
fix bug: no result for contract of shard 4
=> fix a contract query bug
